config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :graphs do
    resources :build, controller: 'graphs/build'
  end

  resources :users

  post '/graphs/new/build', to: 'graphs/build#create', as: 'graph_new_build'

  post "/graphs/export/", to: "graphs#export"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/care_team.rb
class CareTeam < ApplicationRecord
  has_many :caregivers
  has_many :users, through: :caregivers, dependent: :destroy
end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  belongs_to :user
  belongs_to :care_team
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :patient, class_name: "User", optional: true
  has_many :patient_entries
  has_many :graphs, through: :patient_entries
  validates :date, presence: true
  validates :value, presence: true
end

app/models/graph.rb
class Graph < ApplicationRecord
  # Interventions
  has_many :patient_events
  has_many :interventions, through: :patient_events do
    # def <<(new_item)
    #   super( Array(new_item) - proxy_association.owner.interventions )
    # end
  end
  # validates :interventions, presence: true, :if => :active_or_interventions?
  accepts_nested_attributes_for :interventions

  # Entries
  has_many :patient_entries
  has_many :entries, through: :patient_entries do
    # def build(hash)
    #   byebug
    #   create(:symbol => type)
    # end

    def <<(new_item)
      super( Array(new_item) - proxy_association.owner.entries )
    end
  end
  validates :entries, presence: true,  :if => :active_or_entries?
  accepts_nested_attributes_for :entries

  # Patient
  belongs_to :user, optional: true
  validates :user, presence: true, :if => :active_or_patient?
  # accepts_nested_attributes_for :user

  # Type
  validates :type, presence: true

  def active?
    status == 'active'
  end

  def active_or_patient?
    status.include?('patient') || active?
  end

  def active_or_entries?
    status.include?('entries') || active?
  end

  def active_or_interventions?
    status.include?('interventions') || active?
  end

  def self.export(blob)
    chart = Magick::Image.from_blob(blob) {
      self.format = 'SVG'
      self.background_color = 'transparent'
    }
    chart.first.format = 'PNG'
    Base64.encode64(chart.first.to_blob)
  end
end

app/models/graphs/afp.rb
class Afp < Graph
  def self.keys
    ["AFP"]
  end

  def self.parse_entries(entry_params)
    parsed_entries = Array.new
    entry_params["date"].each do |i,v|
      parsed_entries.push({symbol: "AFP", date: v.to_time.strftime("%b %Y"), value: entry_params["afp"]["#{i}"].to_i})
    end
    parsed_entries
  end
end

app/models/intervention.rb
class Intervention < ApplicationRecord
  belongs_to :patient, class_name: "User", optional: true
  has_many :patient_events
  has_many :graphs, through: :patient_events
end

app/models/patient_entry.rb
class PatientEntry < ApplicationRecord
  belongs_to :graph, optional: true
  belongs_to :entry, optional: true
end

app/models/patient_event.rb
class PatientEvent < ApplicationRecord
  belongs_to :graph, optional: true
  belongs_to :intervention, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :graphs
  has_many :entries
  has_many :interventions

  scope :full_name, lambda { |query|
    query.downcase!
   (query ? where(["LOWER(first_name) ILIKE ? OR LOWER(last_name) ILIKE ? OR CONCAT(LOWER(first_name), ' ', LOWER(last_name)) ILIKE ?", '%'+ query + '%', '%'+ query + '%','%'+ query + '%' ])  : {})
  }

  def full_name
    "#{first_name} #{last_name}"
  end

  has_many :caregivers
  has_many :care_teams, through: :caregivers, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def index
    @graphs = Graph.all.where(status: 'active')
  end

  def show
    @graph = Graph.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: {entries: @graph.entries.limit(3).order(date: :DESC).reverse, interventions: @graph.interventions}}
    end
  end

  def export
    png = Graph.export(params[:blob])
    render json: {png: png}
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages(opts = {})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first).try(:capitalize), class: "help-block")
  end

  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag:div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: "control-label") if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end

  def graph_patient(graph)
    graph.build_user if graph.user.nil?
    graph
  end

  def graph_entries(graph)
    3.times { graph.entries.build({user_id: graph.user.id, symbol: graph.type.upcase}) } if graph.entries.empty?
    graph
  end

  def graph_interventions(graph)
    graph.interventions.build({user_id: graph.user.id, type: "Medication"})
    graph
  end
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wicked Graphs</title>
    <%= favicon_link_tag 'wicked-logo-red.png' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" media="all" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap4.min.css" />
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap4.min.js"></script>
  </head>
  <body>
    <section id="main-section">
      <header class="container-fluid">
        <%= render "shared/nav" %>
      </header>
      <div class="container">
        <% if !@graph.nil? && @graph.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <p><%= pluralize(@graph.errors.count, "error") %> prohibited this graph from being saved:</p>
            <ul>
            <% @graph.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/pages/index.html.erb
<div class="welcome-screen row">
  <div class="jumbotron col-xs-12">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <h1>Welcome to our demo application</h1>
        <h2>Wicked Graphs is all about creating beautiful and dynamic graphs. Please select one of the options below to start building your graph.</h2>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <hr>
  </div>
  <article class="col-xs-4">
    <%= link_to graph_new_build_path({graph: {type: 'Afp'}}), method: 'post', class: "chart-option" do %>
      <%= image_tag "molecule-3.png", class: "img-responsive" %>
      <h1 class="text-center btn btn-link">AFP</h1>
    <% end %>
  </article>
  <article class="col-xs-4">
    <%= link_to graph_new_build_path({graph: {type: 'Calcium'}}), method: 'post', class: "chart-option" do %>
      <%= image_tag "molecule-2.png", class: "img-responsive" %>
      <h1 class="text-center btn btn-link">Calcium</h1>
    <% end %>
  </article>
  <article class="col-xs-4">
    <%= link_to graph_new_build_path({graph: {type: 'Insulin'}}), method: 'post', class: "chart-option" do %>
      <%= image_tag "molecule-1.png", class: "img-responsive" %>
      <h1 class="text-center btn btn-link">Insulin</h1>
    <% end %>
  </article>
  <article class="col-xs-4">
    <%= link_to graph_new_build_path({graph: {type: 'Testosterone'}}), method: 'post', class: "chart-option" do %>
      <%= image_tag "molecule.png", class: "img-responsive" %>
      <h1 class="text-center btn btn-link">Testosterone</h1>
    <% end %>
  </article>
  <article class="col-xs-4">
    <%= link_to graph_new_build_path({graph: {type: 'Tsh'}}), method: 'post', class: "chart-option" do %>
      <%= image_tag "molecular-structure.png", class: "img-responsive" %>
      <h1 class="text-center btn btn-link">TSH</h1>
    <% end %>
  </article>
  <article class="col-xs-4">
    <%= link_to graph_new_build_path({graph: {type: 'VitaminD'}}), method: 'post', class: "chart-option" do %>
      <%= image_tag "hexagons.png", class: "img-responsive" %>
      <h1 class="text-center btn btn-link">Vitamin D</h1>
    <% end %>
  </article>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><%= image_tag "wicked-logo-light.png", class: "img-responsive" %> Wicked Graphs</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
    <ul class="nav navbar-nav">
      <li><a href="/users">Users</a></li>
      <li><a href="/graphs">Graphs</a></li>
    </ul>
  </div>

</nav>